[[libjulia]]
arch = "aarch64"
git-tree-sha1 = "081beba13dff1f95eca7f1f39bc9c12ad5d45957"
julia_version = "1.7.0"
os = "macos"

    [[libjulia.download]]
    sha256 = "43040bfb697b913e0b951fddddd9e30eeb74860d433916feb643dfeebf6cb66d"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+3/libjulia.v1.7.0.aarch64-apple-darwin-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3806ad1b5d4bec9862f832a8968b787095b70d16"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "b47d1373f56590d7a35f5ce7923637a0be61a964cd8bd396982d87e6804f499a"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+3/libjulia.v1.7.0.aarch64-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "10becb9b08be44b2bfe626ed246e21ff4913e528"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "099f07de2910ab10bcddaae5074523348ac1df2a713a797c8f8a98c32e6bd5f1"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+3/libjulia.v1.7.0.aarch64-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1703bfd348b178bfe93176f794d204797462f23f"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "b3d8525b66e331157de2cb3188be89b3f0921fadea2cefd4ec9fb044e48d1d96"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+3/libjulia.v1.7.0.aarch64-linux-musl-cxx03-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be99535a6f2aba2ec94f727cf72f26e5ff29ec6b"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "86a522b06542a35191d0e58ac8050a4f6e86abfac016b85e23cccb159ce90ffa"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+3/libjulia.v1.7.0.aarch64-linux-musl-cxx11-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0625769255197ded4e5dd1c277da326ec0fa77a5"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "65801725b6ae37ae4a7ba83260a58f0213cb88b612afca334ac595b6fa324e84"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+3/libjulia.v1.7.0.armv6l-linux-gnueabihf-cxx03-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b6678a40cce71d774ead979486407593f7f8cda"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "2bddf1e485509e1448384f2fc2ba28643d27082759fc75e585bf0443fd5b5b81"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+3/libjulia.v1.7.0.armv6l-linux-gnueabihf-cxx11-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f4b2e70d51b5eddbcd690f33d65b8bfeea02e03c"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "bfe70d0351272a6253f516f097a25d6eba2e8e320121a74c2b07d39d3f0cd15e"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+3/libjulia.v1.7.0.armv6l-linux-musleabihf-cxx03-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "82f665177a1e454e099b3dadb07152f7de57dbdd"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "e486d8aac6ee282852856c3db0288d651fcc476727a7fdb07e86ec0480880050"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+3/libjulia.v1.7.0.armv6l-linux-musleabihf-cxx11-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fdee17153456dc2d55fd43b5d20dbef43a42d702"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "6abe30ff8960ccb90ca247751a000512b22ba07fe76e7d719dbecc58510fd35c"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+3/libjulia.v1.7.0.armv7l-linux-gnueabihf-cxx03-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dad07ceaee6dbddd336aeebaf61faacef9b0ba77"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "f78dd30e58daed5c6a257dc6748ba25470eac6fc240b679b997d7bd312f1bee1"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+3/libjulia.v1.7.0.armv7l-linux-gnueabihf-cxx11-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "690125f768ebdd990a50941943769c88b9875452"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "9a59e1da6027ed45e4bd12e0578aa353f6f514f9400d5b39c4a666291dbe5c56"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+3/libjulia.v1.7.0.armv7l-linux-musleabihf-cxx03-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e7b854bf081823f8d706a1618fa921378d7692b1"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "aecd64418a87b738b74d1fc719d5900309561b9cebea2b3bcaa3e4cc2acc5d01"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+3/libjulia.v1.7.0.armv7l-linux-musleabihf-cxx11-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ec21ff719694a9073fbdbce3a11e8df171dec07b"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "bb6727baaa5d78f568fc0bf1d52d340792aac2708b1c1f12d5607f1f8f3a2f46"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+3/libjulia.v1.7.0.i686-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f13e359b82f9437c39207ef0560d19f2cbe6a372"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "a02edb2843a89dc5998c0d6c0a99d942a8054c8a6685d80b71655f2b4b3c0c5d"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+3/libjulia.v1.7.0.i686-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "67dbe77cd7d84f5358786647d71c7fd588b4aaa8"
julia_version = "1.7.0"
os = "windows"

    [[libjulia.download]]
    sha256 = "f54deca9bbc8d57b5ccfeddeb3c1eacf0e53f856f66e092923e666aaa71a1da3"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+3/libjulia.v1.7.0.i686-w64-mingw32-cxx03-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dcce269a074dccad9477333688677a104fe862d8"
julia_version = "1.7.0"
os = "windows"

    [[libjulia.download]]
    sha256 = "7866b59faa326976f4311716c19e51a25f0752e694eb669daf46cb6cb23c5846"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+3/libjulia.v1.7.0.i686-w64-mingw32-cxx11-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1b7292b253f46517bb87fc109bbe5c20edbba7e9"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "7f76035be2b76617bc45c5edbd1960b12ca67c90c0e817f96d50764f676c1650"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+3/libjulia.v1.7.0.powerpc64le-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8c9f81847c8b1f53f66b8e2d77ba74b7c80fcb0e"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "72122519dea9aa5d4692983035fcf4ddf5a9c565c7b07c3e2dfcebf6987421ec"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+3/libjulia.v1.7.0.powerpc64le-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "x86_64"
git-tree-sha1 = "2fcf6c13aa6a9a2d2ec91e1bbf4fb1c8be8229e3"
julia_version = "1.7.0"
os = "macos"

    [[libjulia.download]]
    sha256 = "834dde9e8e1b07d5df4f4e50d4c8ac91686e0d807cb9e0d82adeb569275e951f"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+3/libjulia.v1.7.0.x86_64-apple-darwin-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0e834da8ceb753143b7669b854e98a57c9cf0e82"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "cdba5c925737352f1de8618001dcd8dd617b62936bfcfde08fca97f7300e5d80"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+3/libjulia.v1.7.0.x86_64-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce16c1bba92ec0a19780860d230935e7df859e55"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "5c36e900c7ff2bfc5a4d938a737caef52738e638a052cb13fbeb9327eb987571"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+3/libjulia.v1.7.0.x86_64-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7cd7b968b8acc3229329abf8fa9b7e6f21e58793"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "be6c6d35be0c14c2ea235805585aee97ef8429f81f8445de9696adcd3e143591"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+3/libjulia.v1.7.0.x86_64-linux-musl-cxx03-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "50a427aca7d48019c34f3141dd07be6521b00d81"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "5d1bb901b5f2fd9f21b6fbe2c4dc48f4e68e6984a7b2fe0ce33025bd76fbbbe7"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+3/libjulia.v1.7.0.x86_64-linux-musl-cxx11-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "x86_64"
git-tree-sha1 = "dda9437434fafd1fa1de3b15a07b7702094fa4de"
julia_version = "1.7.0"
os = "freebsd"

    [[libjulia.download]]
    sha256 = "65dd04b2d7a28f074da9a8a27d5c62a5fdb278e93cf1ccb8c1e74e7c781fbca9"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+3/libjulia.v1.7.0.x86_64-unknown-freebsd-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5ceee9a60c3c12010dcc1d78f4089c0270472122"
julia_version = "1.7.0"
os = "windows"

    [[libjulia.download]]
    sha256 = "52e4cf9ffb865a4e216e923ecef6d3571bebef7235c9e01adcb6e4fefebd3b0e"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+3/libjulia.v1.7.0.x86_64-w64-mingw32-cxx03-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "131b26f39192b2a1751686d4891b13c2375b81bd"
julia_version = "1.7.0"
os = "windows"

    [[libjulia.download]]
    sha256 = "ae994d796fc22e3a4e1da4e1faf540fdad3cc3ae32c29f93fd11997ee32dbc29"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+3/libjulia.v1.7.0.x86_64-w64-mingw32-cxx11-julia_version+1.7.0.tar.gz"
