[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3268a902e6b0c26d8f1c9fc700885e46850ed9d5"
julia_version = "1.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "341eef700e59e91136122e4e9c994d69c9a9d16b03033402feab484c2bf0de97"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+1/libjulia.v1.3.1.aarch64-linux-gnu-cxx03-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d42efc7c0d17bf6dae3ff45465a41cc4f8224ad3"
julia_version = "1.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "bb041a33e8decf3f593c129b68d1941e9815c3356bf00a43abec83034d601a3b"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+1/libjulia.v1.3.1.aarch64-linux-gnu-cxx11-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e2455ec6037ffd9fc98b63490586775009285760"
julia_version = "1.3"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "610dee56cd8aac7ea4132c512f21d56b3aea2447ad0740ad06a3a81a9220af48"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+1/libjulia.v1.3.1.aarch64-linux-musl-cxx03-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "02c33b568fba4bcfc352066a0b9b710d5311ad23"
julia_version = "1.3"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "7352f52fe8dd09cafbe0e5ccf6c3f97f555cbdd7997533826686a2496c55ff98"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+1/libjulia.v1.3.1.aarch64-linux-musl-cxx11-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e708db0f1b4d360ff8cdd3a8a749b8d9a24b89d7"
julia_version = "1.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "497420f9518a3e761069207aec25a4879f5c76c93764151359fd7f0caf4546d7"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+1/libjulia.v1.3.1.armv7l-linux-gnueabihf-cxx03-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "921f298857435a53c381c5cac8bdfb0d4ecd9f38"
julia_version = "1.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "0861ad0cfba618e96b56cb64978f6e1ed93a4ceb6c07b08d67af06ef725cc8f3"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+1/libjulia.v1.3.1.armv7l-linux-gnueabihf-cxx11-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94767a9db4ceede6f4c767a2f48f0d5e96fd08bf"
julia_version = "1.3"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "4fc05a2579584f015a63a6241fd82d772dbffe87bec06a17d5ce81b946a089d0"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+1/libjulia.v1.3.1.armv7l-linux-musleabihf-cxx03-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bdac78edd31d2a527451ad6d48904614ba5744bd"
julia_version = "1.3"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "cac10a0e730795a56c1898f3e3988a90f5c2eb8da0480a6d8310fa5e916b25e9"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+1/libjulia.v1.3.1.armv7l-linux-musleabihf-cxx11-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a0b859ed999fb78cd2a262e73cf2325e5b31eadb"
julia_version = "1.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "3801ee23c71934a6d46a6e466688b11ffbbee0c20977c5779497f0d68188b4cf"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+1/libjulia.v1.3.1.i686-linux-gnu-cxx03-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1405f2e2ba8dd41f063b7663373e62df9bdf72b4"
julia_version = "1.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "2190b424ec42b49fb7863991367f3791b8a4b32442e7c88cc5861a5860aaaf43"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+1/libjulia.v1.3.1.i686-linux-gnu-cxx11-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3b84bfcac6d6bcf553d342ff3bba3d8bc878b6d7"
julia_version = "1.3"
os = "windows"

    [[libjulia.download]]
    sha256 = "8edb03652c27467cef8d0978659ba7aa19afac74abc082e038acb58b6b64b281"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+1/libjulia.v1.3.1.i686-w64-mingw32-cxx03-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c30df670b97ef69204539666f564e443b72c89de"
julia_version = "1.3"
os = "windows"

    [[libjulia.download]]
    sha256 = "ca1739c5f9ed686f2a69aaf8111ad6be26e63245a80bdecc22595f2db677da48"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+1/libjulia.v1.3.1.i686-w64-mingw32-cxx11-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "x86_64"
git-tree-sha1 = "571e228eb2f825580590c8890c6a85f4f1da9daf"
julia_version = "1.3"
os = "macos"

    [[libjulia.download]]
    sha256 = "21c96c4d5ffbcda8904adb84144cd671d46fe959e07fc2ef77345b6584e06ba2"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+1/libjulia.v1.3.1.x86_64-apple-darwin-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7899ca1ecea3e51b6e2dedc2b0106ac8e23b567e"
julia_version = "1.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "2b3f04837682609017338c506271b11208302247d23ae8487e3a927d81a848e2"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+1/libjulia.v1.3.1.x86_64-linux-gnu-cxx03-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0b47104cad896ffa87ead5e97586ff9b55412eaf"
julia_version = "1.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "f194643dc349d9c56d13dc8a3abdedf361015ed2f0ad78c35c198a71bfeeea97"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+1/libjulia.v1.3.1.x86_64-linux-gnu-cxx11-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "04a23aee9db2e476ed95eeb1bd3b8fdd7ab5e0fe"
julia_version = "1.3"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "a07cf5386ae8b83f21a24f56e2d2931cbc170724bca772428136746dcb096cf8"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+1/libjulia.v1.3.1.x86_64-linux-musl-cxx03-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8c8bc50c0d9af833ee60388522027a2422b2182b"
julia_version = "1.3"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "04179080028b92e4f42a796d261b5d0ebedfad129d16fe6f8fb6b3056686d5be"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+1/libjulia.v1.3.1.x86_64-linux-musl-cxx11-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "x86_64"
git-tree-sha1 = "29266526d4a4cede26a366950e2485f355acff14"
julia_version = "1.3"
os = "freebsd"

    [[libjulia.download]]
    sha256 = "7159ef32fc78598021b706f849eea3b40678050f764897f2d68286dd7c5f72fe"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+1/libjulia.v1.3.1.x86_64-unknown-freebsd-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f07b21dbbb80ea91887df50dd36d8ab243d93cf1"
julia_version = "1.3"
os = "windows"

    [[libjulia.download]]
    sha256 = "95e4e3f8746dc0d58b4c89878fc319875db47d275683234a4840b56bd6ee4c47"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+1/libjulia.v1.3.1.x86_64-w64-mingw32-cxx03-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2631db4087a122f5ad7da4393eabc77e19e2fd0b"
julia_version = "1.3"
os = "windows"

    [[libjulia.download]]
    sha256 = "b2c9a010129bac7e2c8f05329e8109d9644cb4d26366bc56216fac52ecac0b3d"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+1/libjulia.v1.3.1.x86_64-w64-mingw32-cxx11-julia_version+1.3.tar.gz"
