[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dfb7f7698f0ec1b5d0b5489c6542427cba9fcad3"
julia_version = "1.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "130b29f3974c3a9f0b49b6a459797ca1dbd0091da6dde48b735eee28abc28dc9"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+2/libjulia.v1.3.1.aarch64-linux-gnu-cxx03-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a4588bb107625ee0a0acc43698d877bea400e9a"
julia_version = "1.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "c177a3d9a93a89cb58401b8edc630a516b2eae8d16600b47fff8b1cc194730f0"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+2/libjulia.v1.3.1.aarch64-linux-gnu-cxx11-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aca8284c16bad3ac02fbb9ee549ad4b5bc90a058"
julia_version = "1.3"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "a30ead1efd19f620123cffa2fb8dca941290860bea3b04bf76be613b756de5fa"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+2/libjulia.v1.3.1.aarch64-linux-musl-cxx03-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "38362d4ea143bc0eb44baf6c138764f61a2084cf"
julia_version = "1.3"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "29545863e70b8ba6ccff382962de8842ec0ff8f7e0d272352cba68c1b4cffb4a"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+2/libjulia.v1.3.1.aarch64-linux-musl-cxx11-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "224fdea162696d08280cce05f44903d1841e482e"
julia_version = "1.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "3499bf64fde82628b3f6805e30ca3d8023a0c30835213e23a70619549d0aacb8"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+2/libjulia.v1.3.1.armv7l-linux-gnueabihf-cxx03-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bbe53eaf4d44dc57058e0403411b81a7236aae93"
julia_version = "1.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "fa585574c751f723b5fedd6251bea7afd3a0ee11c3d0884ddcf5b8e1333504b2"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+2/libjulia.v1.3.1.armv7l-linux-gnueabihf-cxx11-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2f1d1799b69ff75482126619b0d8fdbf9ca078f4"
julia_version = "1.3"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "6456ea84929f570c63a06a6a3b07659a3408be36bbe705083e870fa6a5edc003"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+2/libjulia.v1.3.1.armv7l-linux-musleabihf-cxx03-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "426c0ab84279becf5450dbed1063971d32e11d87"
julia_version = "1.3"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "0415c732ff3806240b34c91b2a84c67e57e4f5e5953a6971be337e5596835fcb"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+2/libjulia.v1.3.1.armv7l-linux-musleabihf-cxx11-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8ac1fd4298409ffe084db59b0a909f5a40aa34ef"
julia_version = "1.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "6d523fefc9ddcb8c7266bede07a55d89c205ccb11fefcd06aa1b2ab90feb88e9"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+2/libjulia.v1.3.1.i686-linux-gnu-cxx03-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef41192c8a53c55df50b40a9898cc4d7b8e5e080"
julia_version = "1.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "dbb87120266294ad20bce8b257315313ed9d169b1469c7461911d121950c0733"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+2/libjulia.v1.3.1.i686-linux-gnu-cxx11-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "111ed727099da957d1c1c854de19e9659dde749c"
julia_version = "1.3"
os = "windows"

    [[libjulia.download]]
    sha256 = "27b117d32b217e710c4e1128c453e1fba3f83bd3905b14f3c473183600141082"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+2/libjulia.v1.3.1.i686-w64-mingw32-cxx03-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d8b3012dd8e68c4ed51fc6cb1a9bd79773d5b193"
julia_version = "1.3"
os = "windows"

    [[libjulia.download]]
    sha256 = "495451fd6ada1c8c0233466baf007723eac23b45f9bc0931bbac0c9b3d922464"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+2/libjulia.v1.3.1.i686-w64-mingw32-cxx11-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "x86_64"
git-tree-sha1 = "5cf004970ce3880e6f608b059770fe26237dea0c"
julia_version = "1.3"
os = "macos"

    [[libjulia.download]]
    sha256 = "de4f1fc21eda918c99af88adc505f710807e3eae1d6f4210e97b0d87bb1f3267"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+2/libjulia.v1.3.1.x86_64-apple-darwin-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ea1fbba7fe7f60cbf0667b77712e5a574556e29c"
julia_version = "1.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "db650a2cf9cd93c672c17f9e203d3c15b9c0c14c38cc5e26f76a9ceb3d17876e"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+2/libjulia.v1.3.1.x86_64-linux-gnu-cxx03-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2ec558d69bf4d003274a2fe73740fcdfe8ec0ab8"
julia_version = "1.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "5732b1c63ae832061fb69bda6b077f8af13d61530bfd1c61cf31ec877d2f80c6"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+2/libjulia.v1.3.1.x86_64-linux-gnu-cxx11-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d8987775ff833049ac1cf67e7e7af2ae53ec226b"
julia_version = "1.3"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "fa6296d034261da85385d4b78aa53e853c4dcc17f6018a146f9cf54d68bab198"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+2/libjulia.v1.3.1.x86_64-linux-musl-cxx03-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6ca6a8da834afca2497da38736cc53d141a1191"
julia_version = "1.3"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "e4059c1eecfa27e6a95257ee20c487795991ce69118faf92472e1f0f8a0f3ab7"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+2/libjulia.v1.3.1.x86_64-linux-musl-cxx11-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "x86_64"
git-tree-sha1 = "4ef2790a88400316e4cfd1928de2fe2fa2fd859a"
julia_version = "1.3"
os = "freebsd"

    [[libjulia.download]]
    sha256 = "cee1ef211ea3098442ca6ad498838dd7ab96cd7bd955addef365b120af5b783b"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+2/libjulia.v1.3.1.x86_64-unknown-freebsd-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "901a4a158644acab5a9ba46c0ebc72a5da71c174"
julia_version = "1.3"
os = "windows"

    [[libjulia.download]]
    sha256 = "5424a4286197d4279edd189dbe942c5d12520f0b75be07762ce1c0defef36539"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+2/libjulia.v1.3.1.x86_64-w64-mingw32-cxx03-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "93384a3daa0d89115703dc7cffe00e1de46746e2"
julia_version = "1.3"
os = "windows"

    [[libjulia.download]]
    sha256 = "b5add80613ccf327f25c17ded4bce65f08ff6ce87c4a85cf38e841df65c5ecb0"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+2/libjulia.v1.3.1.x86_64-w64-mingw32-cxx11-julia_version+1.3.tar.gz"
