[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bfe765838dc33c69a120e043c3cce1e137dd24c2"
julia_version = "1.5.4"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "b901c9bf86df319a13e90cd7cc9cd947a9c70b5af1212966807af0e5eaa1218a"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.4+0/libjulia.v1.5.4.aarch64-linux-gnu-cxx03-julia_version+1.5.4.tar.gz"
[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b9954f81d934e669a8bc433667d3c84dd92440cf"
julia_version = "1.5.4"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "8d45481022faede0453035c2eecbca33c844cd175d6660cbccf892c86bcd47f0"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.4+0/libjulia.v1.5.4.aarch64-linux-gnu-cxx11-julia_version+1.5.4.tar.gz"
[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9ce8f93463f11889d78f8eb479fac2229acc6813"
julia_version = "1.5.4"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "3fa5832223935e228696508f64daeff63703aa0bf23326b6d3ca66eecc560a4f"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.4+0/libjulia.v1.5.4.aarch64-linux-musl-cxx03-julia_version+1.5.4.tar.gz"
[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "938f05417b5ff4f0da6071cba7830451a1f17b29"
julia_version = "1.5.4"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "2769593db5c5c95317e0dd6454497821582e6a9e000db7ae50409dd68f748475"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.4+0/libjulia.v1.5.4.aarch64-linux-musl-cxx11-julia_version+1.5.4.tar.gz"
[[libjulia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8dd8810cd4c59bdbf7d3e003f3d11c58d9e0b8a7"
julia_version = "1.5.4"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "0da2a6c35f7e3e65c62ec59ff1440b21402dc8834e1ecd1df17a05addbc7dc8c"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.4+0/libjulia.v1.5.4.armv7l-linux-gnueabihf-cxx03-julia_version+1.5.4.tar.gz"
[[libjulia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4087c0aff2245aaa1614aa3fe22eb939ba07ede8"
julia_version = "1.5.4"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "561eeb87f85ace8f8c19badc470c8a9afd3083fbea49ec98ecab9bd26cc5b956"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.4+0/libjulia.v1.5.4.armv7l-linux-gnueabihf-cxx11-julia_version+1.5.4.tar.gz"
[[libjulia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1b0528fd8c0e6810e70fa2c33ae6cdbcacbc1323"
julia_version = "1.5.4"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "3081ff3282080a9ceb1781675ec4ac2f8ffeed3e19f68ada7c15fb52a3c2b512"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.4+0/libjulia.v1.5.4.armv7l-linux-musleabihf-cxx03-julia_version+1.5.4.tar.gz"
[[libjulia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d61b1fc8409f42a1b1629fdc3add498ee92248bc"
julia_version = "1.5.4"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "8e3dcf11a7c1c6d60051144351546fbb826702eb0de18fc6cdc66b2b20aed703"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.4+0/libjulia.v1.5.4.armv7l-linux-musleabihf-cxx11-julia_version+1.5.4.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "74d06155eedb61a12ef070a56c3ef0157426e5e0"
julia_version = "1.5.4"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "a3bb1c5da362f401baf8736358ea5c09b35715922e524df0cb1518081cf3839d"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.4+0/libjulia.v1.5.4.i686-linux-gnu-cxx03-julia_version+1.5.4.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9037b66fda01733217d0a5f8b46a74ce2564cbd9"
julia_version = "1.5.4"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "3f57a09986171dda6f73f8072a5f6a195fd337d537d2f0cf31013d0f97351ca3"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.4+0/libjulia.v1.5.4.i686-linux-gnu-cxx11-julia_version+1.5.4.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cc0cf8947dfdb888dae3c1a714bdbef0de82b64f"
julia_version = "1.5.4"
os = "windows"

    [[libjulia.download]]
    sha256 = "98d212b42c9f6c6b871836a86c1a5d9fbffc8249929a375e6a5fd9b3eb840e29"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.4+0/libjulia.v1.5.4.i686-w64-mingw32-cxx03-julia_version+1.5.4.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3885938958486bb82cfe5297f6188b7f6af663e2"
julia_version = "1.5.4"
os = "windows"

    [[libjulia.download]]
    sha256 = "c2dfa0012c4bd3e6a1147d9e6d6ecd4f1cd9d8068ac74bba6caa0e792a46fd3c"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.4+0/libjulia.v1.5.4.i686-w64-mingw32-cxx11-julia_version+1.5.4.tar.gz"
[[libjulia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0fc4d8fb1e3b4ae06d2d3d4b0b75865786a1354d"
julia_version = "1.5.4"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "c0882142d632fe9a3e3bce57331ca4d2eac6332d01362412cc530ac29b329c27"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.4+0/libjulia.v1.5.4.powerpc64le-linux-gnu-cxx03-julia_version+1.5.4.tar.gz"
[[libjulia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4162bc60ce528bba901b15079b580c6c3345dedc"
julia_version = "1.5.4"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "2ffc632b6e865df2aaabbc8262eb746e60b14712aac6dbd536002c69a4ab5b79"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.4+0/libjulia.v1.5.4.powerpc64le-linux-gnu-cxx11-julia_version+1.5.4.tar.gz"
[[libjulia]]
arch = "x86_64"
git-tree-sha1 = "5f18b8ffcf077645b0590bc8277307f58cf05147"
julia_version = "1.5.4"
os = "macos"

    [[libjulia.download]]
    sha256 = "559b5c4f4091bb27b495f04fd565cdb04212b286ea6be69c5db2f61ddf7fe4df"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.4+0/libjulia.v1.5.4.x86_64-apple-darwin-julia_version+1.5.4.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7ea1faa0bdb03524783d08d510b7e4d696157d4c"
julia_version = "1.5.4"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "97cf15d3d001770d13ed26adb5bd10cdfdf5e547e1a8815e7725f6ad18ff615a"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.4+0/libjulia.v1.5.4.x86_64-linux-gnu-cxx03-julia_version+1.5.4.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6966fa5223f6abb6475ef467836331c0e51226aa"
julia_version = "1.5.4"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "58eb653f3f0baa71583fb8d942a7f660030d988df33f78e0b755fe0178a8545f"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.4+0/libjulia.v1.5.4.x86_64-linux-gnu-cxx11-julia_version+1.5.4.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "48db3fac6a5de25035e9b8a43fb9e87435bd4c0d"
julia_version = "1.5.4"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "4bee70e5c01160931382a32e02be80c3274b71ebf2c7420a36f348443b153a65"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.4+0/libjulia.v1.5.4.x86_64-linux-musl-cxx03-julia_version+1.5.4.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b24bbaa1e3805b4787c87b56f117d10783ca583"
julia_version = "1.5.4"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "464b07e1f23a71fd32b1df68f74719e17b0c3e08dc9b736446fa97e8107d19c4"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.4+0/libjulia.v1.5.4.x86_64-linux-musl-cxx11-julia_version+1.5.4.tar.gz"
[[libjulia]]
arch = "x86_64"
git-tree-sha1 = "b58506c683ddb3fd54ba602a4914f95bc79adc75"
julia_version = "1.5.4"
os = "freebsd"

    [[libjulia.download]]
    sha256 = "0538c0783074a56bda4da98386065937070efd6e3ef209c1c8d968e152036648"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.4+0/libjulia.v1.5.4.x86_64-unknown-freebsd-julia_version+1.5.4.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6c9cb259ee06692aefddb989e04fec674939587f"
julia_version = "1.5.4"
os = "windows"

    [[libjulia.download]]
    sha256 = "5752934cfadbba7888700c9e2468f1bceb2a9cd69a0169d1d5634ed2cb5ad6b8"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.4+0/libjulia.v1.5.4.x86_64-w64-mingw32-cxx03-julia_version+1.5.4.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c7b0ced41538208ac061225ae8b51c89b09302b"
julia_version = "1.5.4"
os = "windows"

    [[libjulia.download]]
    sha256 = "1905f5bf5c465135e453688d313a39a28cd0b995a6e3180c6a328c4d689a0d7f"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.4+0/libjulia.v1.5.4.x86_64-w64-mingw32-cxx11-julia_version+1.5.4.tar.gz"
