[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8e7bff917e17d8617094d0a8e65c28c8b4030e42"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "e5b26caff5e90302c13a72dcec7831af82ceb41b24f0047c73b45ed8c251e781"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.6.0+0/libjulia.v1.6.0.aarch64-linux-gnu-cxx03-julia_version+1.6.0.tar.gz"
[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "de9e8a09ac8cd29af13869045056563e380421fe"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "3ffec8434465109c27c17e70a57134137c3f23f5d356281f4df4d736c040a69e"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.6.0+0/libjulia.v1.6.0.aarch64-linux-gnu-cxx11-julia_version+1.6.0.tar.gz"
[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bffefd0ef88b87bb64bd81ae8ceb23c26e7740d0"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "fe5f679574966d7cdbfe55637a38e93471f0bfeb277c3d0cbd4d0b479c200180"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.6.0+0/libjulia.v1.6.0.aarch64-linux-musl-cxx03-julia_version+1.6.0.tar.gz"
[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b71c197005ab766bfc91bc656b9a2b0911be772a"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "c28efaf072b1b6159b6ead2d12182fa5547707a68b3334902136f458650296f1"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.6.0+0/libjulia.v1.6.0.aarch64-linux-musl-cxx11-julia_version+1.6.0.tar.gz"
[[libjulia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "247e8d0fcaea1a6cc3c2c9d7c50880016c0a2732"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "508cbefdb52968781744cb7c41c00569d80d0d18ce6b59e8edecdc8d7c05bfff"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.6.0+0/libjulia.v1.6.0.armv7l-linux-gnueabihf-cxx03-julia_version+1.6.0.tar.gz"
[[libjulia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "df74ef5d02fc1b74318571c5d14e711a041cdb5e"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "573edd1f58f6d592eea4b101bb1f504aec2b6fcb3cbc3f14b0ba50b1059b4a96"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.6.0+0/libjulia.v1.6.0.armv7l-linux-gnueabihf-cxx11-julia_version+1.6.0.tar.gz"
[[libjulia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6e062af09aedb5ca75bf82c43b8406d79f8e0a58"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "200ff06e305dd2a8be3e33c8151aa86ae882b9c997645b4ad18eac008ef6032a"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.6.0+0/libjulia.v1.6.0.armv7l-linux-musleabihf-cxx03-julia_version+1.6.0.tar.gz"
[[libjulia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "45388a3f0537dca01b3904a75b3073c503f3ecd3"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "548d68a071ac2a66d95d675a1d54fb753c7964000e41162302833792b0701802"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.6.0+0/libjulia.v1.6.0.armv7l-linux-musleabihf-cxx11-julia_version+1.6.0.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9f724e4ab3ed1d72df5403c7c7ffc92f08c9f5d5"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "2c9ba068b7a29482c9153285a7d879116d9a0918b944ff1e040a58311ff0aea6"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.6.0+0/libjulia.v1.6.0.i686-linux-gnu-cxx03-julia_version+1.6.0.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "09c01daa6b848d0ba9a5d0c55457c8373ec47c9e"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "a6fc948018b32d619e5ab1cae1047e236bded9cfc345d0c856bc981741d836eb"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.6.0+0/libjulia.v1.6.0.i686-linux-gnu-cxx11-julia_version+1.6.0.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "47be7da65b907adc4ac65cb49ffd6990dbe4dd4a"
julia_version = "1.6.0"
os = "windows"

    [[libjulia.download]]
    sha256 = "17e4f4a194e8e19592679addd98ec07d7a8ac6a1ea4aeddc8c3ca138f031f5a7"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.6.0+0/libjulia.v1.6.0.i686-w64-mingw32-cxx03-julia_version+1.6.0.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "05ad1ee41a4f348bfc08db7ec802aa43b770aeda"
julia_version = "1.6.0"
os = "windows"

    [[libjulia.download]]
    sha256 = "81cdac0a3db42af800cfee5626f7807b87ef1074cffc1983b745b39d55d5e9f3"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.6.0+0/libjulia.v1.6.0.i686-w64-mingw32-cxx11-julia_version+1.6.0.tar.gz"
[[libjulia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bf6f2aecf109507784996f4e75b0fc69ec65f30a"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "8b9ff7f7f68014110c9c9c59cd0936cba37bd32c7729d3401ec39e434d6f74e3"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.6.0+0/libjulia.v1.6.0.powerpc64le-linux-gnu-cxx03-julia_version+1.6.0.tar.gz"
[[libjulia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "deed413afffc268767575c3efd1c33ffefbb8172"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "52ba01225886a386f560912e5f3054cec15cd9ddb9a4a0d1df1ac81d81a73c04"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.6.0+0/libjulia.v1.6.0.powerpc64le-linux-gnu-cxx11-julia_version+1.6.0.tar.gz"
[[libjulia]]
arch = "x86_64"
git-tree-sha1 = "c71061e6da32def3d0013981519f001ecd8bb471"
julia_version = "1.6.0"
os = "macos"

    [[libjulia.download]]
    sha256 = "11936ee0f47a5e19aac4a296cfea59ff1a09a4a1c93d7529f692546404a08531"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.6.0+0/libjulia.v1.6.0.x86_64-apple-darwin-julia_version+1.6.0.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "39eca94db865f27794230c5a6977ac0b7cf2cd94"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "daad5b0b52cf9f289eccb18b1f3a0493d0f44db4f4efc8f030f714b82a389876"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.6.0+0/libjulia.v1.6.0.x86_64-linux-gnu-cxx03-julia_version+1.6.0.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e6b737019c0bc4383a803e63fcf5ab22840b3bd"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "bf2338934d3563d33a2d0378c9add38841334ca2fa3d26886fe20da1daf70864"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.6.0+0/libjulia.v1.6.0.x86_64-linux-gnu-cxx11-julia_version+1.6.0.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e2379d656fb29cf98d8646c692d1a9d05466806e"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "677afe21281d0d3f6de5f9ec22a9e0573bf171c985ce133f759af1c703291207"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.6.0+0/libjulia.v1.6.0.x86_64-linux-musl-cxx03-julia_version+1.6.0.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d8ff91e3819ad8c288951e38dc87fec4847c29ac"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "aba2c73c4c4c9bed4fd68de9919c37583be053643f432a8d72bf75fc7ba886af"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.6.0+0/libjulia.v1.6.0.x86_64-linux-musl-cxx11-julia_version+1.6.0.tar.gz"
[[libjulia]]
arch = "x86_64"
git-tree-sha1 = "2d68b882601294fe9aeda5696f0ffa76f1c2cf14"
julia_version = "1.6.0"
os = "freebsd"

    [[libjulia.download]]
    sha256 = "2c7d516b39f4c74f2ae74d818cbbf4b9a7eb854c5edc4d9add590c6ecd580b0e"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.6.0+0/libjulia.v1.6.0.x86_64-unknown-freebsd-julia_version+1.6.0.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9870fec5efb76d20605e9e9bdfbd1b68e82f894b"
julia_version = "1.6.0"
os = "windows"

    [[libjulia.download]]
    sha256 = "9a3e47bf3df769950fcc8eacf65c65d0af73060e97ee451ca78b4ce6410d8991"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.6.0+0/libjulia.v1.6.0.x86_64-w64-mingw32-cxx03-julia_version+1.6.0.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "07bfb7028b0800d36134634855cb5c608deef64f"
julia_version = "1.6.0"
os = "windows"

    [[libjulia.download]]
    sha256 = "9deeb2a8779c672417cfde55e111277c16efe5cff5307c206b5497f8d7ce263a"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.6.0+0/libjulia.v1.6.0.x86_64-w64-mingw32-cxx11-julia_version+1.6.0.tar.gz"
