[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "610169a2864e1bfc2679b8af520e5e22ad1789df"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "9288992178c0f327547a5e1e86a2512bf2cb10e7cfa1e5835783d691f8f922ba"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.1+0/libjulia.v1.5.1.aarch64-linux-gnu-cxx03.tar.gz"
[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0aaf17271297e5d98f339677a012d69d673c228b"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "9eeb29cbf8060c545f620876883bc853f8a965a4751b4ee3f3a2144e9560f1cc"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.1+0/libjulia.v1.5.1.aarch64-linux-gnu-cxx11.tar.gz"
[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e5cc1a68ddb2ba048d83cc476377fbe0a7cd4cb6"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "a46e17e8d1e818f99f78f68a567d8687330326e04c98bcb711a82f29b4fedaab"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.1+0/libjulia.v1.5.1.aarch64-linux-musl-cxx03.tar.gz"
[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "79de6593ba5b64f7f666e95d490c4db54cb501f1"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "74f9b10a302780dd14cb5dd09f36bf8a67944a63228c145962baca2e328e21fc"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.1+0/libjulia.v1.5.1.aarch64-linux-musl-cxx11.tar.gz"
[[libjulia]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7d42c327d669173c4d644d1ef63b914de1c4d3d9"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "3e9035fe198b073817db17ff90323f2d5dabf0269659cb44018a4a45d549349d"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.1+0/libjulia.v1.5.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libjulia]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e3113ad8962b145649e68f290808563a08d158bb"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "1a9578aeb2055f48dcb4bf5cb9763ecbf974752a123bac7d769b0eeba40bbf8e"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.1+0/libjulia.v1.5.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libjulia]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6e1c9aad0ca2c660f0fe0be307e8b5f6f1db1de9"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "ff77428f31f58ba49b028e1aa72da6608ec318db638d383e82b31f3cd5c1deea"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.1+0/libjulia.v1.5.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libjulia]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2dd37df398c3e3b387152a044b7e1cd678c61fb7"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "15b43c3d47bc5cdba24302b7aad4f49cc10fc62a709764f67e012af571f5c17b"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.1+0/libjulia.v1.5.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c2543d245dad87777c47a4966736ce9eacca0f27"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "cb150a865791ece1dc7e2b6814115d6a212e23dffcccbbe87b1561b3ef4d99c7"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.1+0/libjulia.v1.5.1.i686-linux-gnu-cxx03.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "523cc7debe1c50887a41b3bca386d780e69444f7"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "e4baaee6af9ad616c3a6d91accc79cad98ac2a33daa1a6df7e0051ac2575ca0f"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.1+0/libjulia.v1.5.1.i686-linux-gnu-cxx11.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "11811a4f3422d1b4ab841a2a08b0105aaeddd3b0"
os = "windows"

    [[libjulia.download]]
    sha256 = "fb0dda3c1db288bab059fc87d724ac7abc89295bfcf7f23be05d3d34a86e2690"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.1+0/libjulia.v1.5.1.i686-w64-mingw32-cxx03.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "37a4052fd1bcd7622d1d63499cb0cdb748ea9fb4"
os = "windows"

    [[libjulia.download]]
    sha256 = "becc43f2ce04e04ab4fff124bb72dbdbf802d9dacf6e2d315ee787b76bd9944c"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.1+0/libjulia.v1.5.1.i686-w64-mingw32-cxx11.tar.gz"
[[libjulia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fa3858ecf2a4776685f85b483c6b06f37c40b31a"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "45df2f9eea138bfc43c99311431e816e301885de0466c8a25606f67bd90621b2"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.1+0/libjulia.v1.5.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libjulia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7aa1a544a261930f4284519363c7aa511e024a54"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "782d3d3304e81b5f6b2b0f2dfd50ef44674ddc453bfc64465ac5203add3743a5"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.1+0/libjulia.v1.5.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b73321cc837671543b9ce95680dfdaea44c9a4ec"
os = "macos"

    [[libjulia.download]]
    sha256 = "4d4e258d6fb936b1fd914cb44256e6653e8a43e5c67340b22c3c03f6cb6307cb"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.1+0/libjulia.v1.5.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "68306f3cb218faaa19c18fc11c392ff306be5d45"
os = "macos"

    [[libjulia.download]]
    sha256 = "715697f1fa3f015c5f535a3bd170378c08aaf3878fd8ecbfb069776de79a6a7b"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.1+0/libjulia.v1.5.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "35d876c4172ceaac1aaa64ba17d7059e968fe09b"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "bd7110ca57f653c962e97c972d32633d481cabefcf134e7dc097aad8ad95d2ad"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.1+0/libjulia.v1.5.1.x86_64-linux-gnu-cxx03.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1fee6acc39594f86146cdbb7cbcf119330a78f30"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "d6cd8c54b6ddce586c70ac01dec4b04eece6c6a451c4e34186d26422ba542569"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.1+0/libjulia.v1.5.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "91220ac3e468cb4a7caa80b0bd383f9d3676ec9b"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "ac2c4515558cdbce92b50b8e112cd18a8b8e2d31e2a0684b95a1f903aa9840c8"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.1+0/libjulia.v1.5.1.x86_64-linux-musl-cxx03.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75bd9403a494e0b252a74eca24226bcf9a4b1ccc"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "10523576a1983e1de77ac3fc4341d5f5d5e4104b33969bde8576c0e48a70484e"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.1+0/libjulia.v1.5.1.x86_64-linux-musl-cxx11.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3730ce781476118bd6fdafd4980d03438ca2e056"
os = "windows"

    [[libjulia.download]]
    sha256 = "12789d3450d4ada2a933305a8fb57198fb256f52f54cb74a2649401a4bb32171"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.1+0/libjulia.v1.5.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c0f29267dc15e5cc35a0ad1d2e889e419702eb78"
os = "windows"

    [[libjulia.download]]
    sha256 = "23edddff135b2820a3627e17022425a451acd86470795321f67f8ba39a862d60"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.1+0/libjulia.v1.5.1.x86_64-w64-mingw32-cxx11.tar.gz"
