[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2b7613c5be18375bacf718a4740463faf0feec4a"
julia_version = "1.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "6452669d485c4f18f6d8065bf545d50c4671a1000aae9236af74092ce2693ced"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+0/libjulia.v1.3.1.aarch64-linux-gnu-cxx03-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e3e77113eb0d1139278cc93738619c36b71bfde"
julia_version = "1.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "0d0a425f9765a2c17360cc6e5f031b8c160791e26df5fe46ac1f39bf20689a68"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+0/libjulia.v1.3.1.aarch64-linux-gnu-cxx11-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4a61c5de1fbe17bf9c43ea4c13b8ae8ba9d5e8d3"
julia_version = "1.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "07ea1abf39325c03d5396f28fef0116fae172b81cf50a79d5ac2076bab42a5d1"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+0/libjulia.v1.3.1.i686-linux-gnu-cxx03-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "40a3246184fef6bd765428a23e6a0c6bfc9b2387"
julia_version = "1.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "00d735683035268a19fe4178f6f235471f4679c5208eba0beca6ba0a6a88aad6"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+0/libjulia.v1.3.1.i686-linux-gnu-cxx11-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ab16c5d09adb83c96ea2f39c95cba8b46acdcef2"
julia_version = "1.3"
os = "windows"

    [[libjulia.download]]
    sha256 = "ed041fbbf15907683924e751ce2e596ec6d16aff7d8661771d4b366e1ab932e3"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+0/libjulia.v1.3.1.i686-w64-mingw32-cxx03-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1097209fd85a0207c0d6a5d8045945f6b37f469b"
julia_version = "1.3"
os = "windows"

    [[libjulia.download]]
    sha256 = "1cb98d59f1732ba77c6ae311ed4ce6f86ed988426dcebb4e37c3044229439890"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+0/libjulia.v1.3.1.i686-w64-mingw32-cxx11-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "x86_64"
git-tree-sha1 = "3b5562ac8beba624254f9aa31bd617837d46993b"
julia_version = "1.3"
os = "macos"

    [[libjulia.download]]
    sha256 = "36e42ae52f4391e628ba48ffa54cc5c073102d822b6cca4100190ff5b522cafb"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+0/libjulia.v1.3.1.x86_64-apple-darwin-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eb8ce2ebed88c2912b1a60f86faefe2d801d489e"
julia_version = "1.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "bdd5a7440be72612662d90a3da51bf9ddc9af97850da9108d804b84abe3b7bd6"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+0/libjulia.v1.3.1.x86_64-linux-gnu-cxx03-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f7c62642f45eb96a5cab9142ab79d904c73d8a1"
julia_version = "1.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "0280ce5901099a93ca4202c8e65405fb2e3a03cb38c984d2c960ba981c1fef2c"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+0/libjulia.v1.3.1.x86_64-linux-gnu-cxx11-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "91f26eb7480b6e1bb8f1a1ca9f1da6d25d9e851d"
julia_version = "1.3"
os = "windows"

    [[libjulia.download]]
    sha256 = "e30bb9839a6095b08b751b5e5797e026910f02720c7fd3f755ca433bfc98a14d"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+0/libjulia.v1.3.1.x86_64-w64-mingw32-cxx03-julia_version+1.3.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5aa8630213bc024ec23844862e9f3c1f84ef2f05"
julia_version = "1.3"
os = "windows"

    [[libjulia.download]]
    sha256 = "9beca8afdae05796397d1b38ca65c136ebbebdf05bd8910b7f8fa09e9f8ffd4a"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.3.1+0/libjulia.v1.3.1.x86_64-w64-mingw32-cxx11-julia_version+1.3.tar.gz"
