[[libjulia]]
arch = "aarch64"
git-tree-sha1 = "e9797bb00fa91ae8b2b68607ffc7900fbd606647"
julia_version = "1.7.0"
os = "macos"

    [[libjulia.download]]
    sha256 = "f64e1827161d5e50f07dc8b4e3ca9d6d406cb03ccd868fa98140e8f9216d3063"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+2/libjulia.v1.7.0.aarch64-apple-darwin-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fe585707337b855e1392a17e74acbf7483e61336"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "7e4ebc4cbccd7fd8a41f1f962ecadbba1aa6f1908abc42c4663d14923c5c2ee4"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+2/libjulia.v1.7.0.aarch64-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5bf7038b2ee4ad25c02d5bbd88a8122088217b09"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "cadc5f628c574a434295d2f6fe489123b149a5b0cbf803320a0ca79eff964f5b"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+2/libjulia.v1.7.0.aarch64-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cbb67bb1591510d17a0b59ff24f29f1f0a8f7b2e"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "d66090855530d3f5d3a329c2e6ef568bab1a43c1b1717c48fbde138cb7fd0f1a"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+2/libjulia.v1.7.0.aarch64-linux-musl-cxx03-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b8374ae7f0d87bf96fbd6eb4d15e1f2ce6e36bf"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "29bfec91b4c30b543d903fd8000ff89511f2c2e3d43933a96c9042ab9f26f647"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+2/libjulia.v1.7.0.aarch64-linux-musl-cxx11-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e2230d63607138f2ede9dd96040ec3b59390bee6"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "07f1fb10d873b4e81d01c5297d363f417278a27d665dd218cacad902467d84c2"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+2/libjulia.v1.7.0.armv6l-linux-gnueabihf-cxx03-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be5b17ec8c19b9825e46e9a545792dbabfcd2e9d"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "f2ed59b5f433ad32dcf7a7871ea5ea470233b9258feaca597610b43c60be63d9"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+2/libjulia.v1.7.0.armv6l-linux-gnueabihf-cxx11-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "484125d2f5a51895e966c67a439f94b2ab48ecbf"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "f4419656a02d513c16c613c439f9fe164d86b6270a3f92f27bf568a50e465be1"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+2/libjulia.v1.7.0.armv6l-linux-musleabihf-cxx03-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95f06af0008967dd35a45dfb2703b1f4b90292c5"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "9d6cd9367593649012db7ddc660f6f03f4f0dc5fe733a6c11ef0a16915ef1fa6"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+2/libjulia.v1.7.0.armv6l-linux-musleabihf-cxx11-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ccce52bb3e8681af2365a879de3ebbba85ef071c"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "d770a3031ca6beb76d66342ec23e5be1b7519858d40883a945253a1dcb515321"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+2/libjulia.v1.7.0.armv7l-linux-gnueabihf-cxx03-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3960d2347be26f4191ad0260119ed32b0b36e8d0"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "33584a0ade6cae7c2c3c83315969294a471ad5d729dc1d42df8a800eb6cc2a34"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+2/libjulia.v1.7.0.armv7l-linux-gnueabihf-cxx11-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "148cbd89c84a9b182f8c7ee76fdeaecb85aeb513"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "4865c904fc0d172365135c7fc5ebff748de9ec5ba056e2db36721d75e16a61cd"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+2/libjulia.v1.7.0.armv7l-linux-musleabihf-cxx03-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a5740b316feb06ab20593a49be17485b0a1fc45a"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "9b213c5bc58580aa902c0d0b5d1e959c7556912d5e98ce1e7cba2a86e670e52f"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+2/libjulia.v1.7.0.armv7l-linux-musleabihf-cxx11-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a5cd78d0d1b46aca9a2fc1baeb6ce31158493355"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "33bb9c1727c2cfd781e2b8d9f74ac1d9338adae31e295fb5b066fbca857fb619"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+2/libjulia.v1.7.0.i686-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e7a77ecd384fae4f097a9467f426ab0ff4e07cb"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "81a5d88cc208e610c37eda64db30eaf20f4baa0df472d5fc9ac94882b1b2fadd"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+2/libjulia.v1.7.0.i686-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f165a1a8908f7371027cf73a149f3650e7c17e3f"
julia_version = "1.7.0"
os = "windows"

    [[libjulia.download]]
    sha256 = "404bf55009f4d75a646e4453b8791003fad47b9cae66ce07fb3c4855f5e51b62"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+2/libjulia.v1.7.0.i686-w64-mingw32-cxx03-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "656cc11b0bd5638da034eead349176130b1d8aae"
julia_version = "1.7.0"
os = "windows"

    [[libjulia.download]]
    sha256 = "f49dbb95d727ef9cf36d22958fdeb9b61ad32140fcb29189bfb1c309d7b95f66"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+2/libjulia.v1.7.0.i686-w64-mingw32-cxx11-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0377c179f1fa18d9efe3d4a8cab806a039499e66"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "4d893a078cef4f33ad340343f0dd0ed6df33a230bcf275a5ce983bfc349d30c5"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+2/libjulia.v1.7.0.powerpc64le-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f21ec05c8397953768914b430f7246d56169fcb"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "75be7c63168d2f39dc824b63eef512c798013352aeb55dbb5f46cac0e613fef3"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+2/libjulia.v1.7.0.powerpc64le-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "x86_64"
git-tree-sha1 = "a78a7d8138c6ce5ff6861856a47cc6f62433ba29"
julia_version = "1.7.0"
os = "macos"

    [[libjulia.download]]
    sha256 = "2ee8b92dd2247f220c49be055d7c05bad4969893ef508007669576fb32c9decf"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+2/libjulia.v1.7.0.x86_64-apple-darwin-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eaa5d2228fbe6adf88e0f952e282f1c850adf044"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "04d2c213fb9feb59c9238a90c875d83b5952ec0ae5376c8bb58c76bb94df429d"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+2/libjulia.v1.7.0.x86_64-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd7c429712c66a6d3beecc6f7ca0931414ca8f85"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "b00e6cedf62b9ef259e0946387f9733eebd54f2d106fcf23d1a4b749b26639b6"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+2/libjulia.v1.7.0.x86_64-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f354f364513741a3eec39a4df9c3794a01b7765a"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "0a5a241331dfb7fb7e5eaa744312fb998b655532b55af822baaf7522892e97a7"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+2/libjulia.v1.7.0.x86_64-linux-musl-cxx03-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c433371ba41099296d376355d00d6765f89f3caa"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "1f1ad4a19fd43cdada54c502f70f43f13a58b4d81f40887068640239d47752ad"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+2/libjulia.v1.7.0.x86_64-linux-musl-cxx11-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "x86_64"
git-tree-sha1 = "342bc087f76238089b3728a3632c59ba0f2eb2ea"
julia_version = "1.7.0"
os = "freebsd"

    [[libjulia.download]]
    sha256 = "182a6a7f1ffabddbd0308a140ed2dc74fa8dfe075929f8247d8580c505be1b75"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+2/libjulia.v1.7.0.x86_64-unknown-freebsd-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "571f42809559ff8ce9db088c019a7f8787c31d84"
julia_version = "1.7.0"
os = "windows"

    [[libjulia.download]]
    sha256 = "83890d1679f8180a7debe0ca45764d690972c63fa0ace0e3769f97ee32736e22"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+2/libjulia.v1.7.0.x86_64-w64-mingw32-cxx03-julia_version+1.7.0.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c262a16129177223887571a1ee0444ab4415234"
julia_version = "1.7.0"
os = "windows"

    [[libjulia.download]]
    sha256 = "422fbb609393cfba8803f351d23ed22bd1f6a7c7d524876735c47c0f2b8e50b6"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.7.0+2/libjulia.v1.7.0.x86_64-w64-mingw32-cxx11-julia_version+1.7.0.tar.gz"
