[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5160421dd9f97ff7f1f6f96c62e53e5afad9f322"
julia_version = "1.5.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "ab045e1352dcb126b65f65b9525ea9e72f0004ba556b56d9f3450688aa74a7ff"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.3+1/libjulia.v1.5.3.aarch64-linux-gnu-cxx03-julia_version+1.5.3.tar.gz"
[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a2effa2dc2aa095263dd0c2d14a6cdc8dd7f83e"
julia_version = "1.5.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "78e6dbee92decbfaa723d9d78161ce9bdfead87e0a4eda7f7594fa06a5060917"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.3+1/libjulia.v1.5.3.aarch64-linux-gnu-cxx11-julia_version+1.5.3.tar.gz"
[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "25f8267443b2550abfd65a56b394b43dd6c18c42"
julia_version = "1.5.3"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "b3939482e11cb6f8f50f863dd29f077f95633aaa4c4aa5e92b6ee95d9d389b58"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.3+1/libjulia.v1.5.3.aarch64-linux-musl-cxx03-julia_version+1.5.3.tar.gz"
[[libjulia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2053ec0c2108b1880324c9c509e1a5ad8d9df69b"
julia_version = "1.5.3"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "0ee6cc6e8f3baaba576c0703cc373edfa6408ff2addebce930a1e8ef7b5c3bee"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.3+1/libjulia.v1.5.3.aarch64-linux-musl-cxx11-julia_version+1.5.3.tar.gz"
[[libjulia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8c1ad30954e6e0f8c251d977b0415c702fc0aa0d"
julia_version = "1.5.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "68f02404c4aa9f3fc9aefdf14cf23b93627c741c85d4f567c776957e44c12544"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.3+1/libjulia.v1.5.3.armv7l-linux-gnueabihf-cxx03-julia_version+1.5.3.tar.gz"
[[libjulia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a181ffcc111908a7d4abf7267b03a32c46b0ac5"
julia_version = "1.5.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "f03d3316c601d5798f36b16db799d76712daef1e8b8b57abe8e3822bf6bb7797"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.3+1/libjulia.v1.5.3.armv7l-linux-gnueabihf-cxx11-julia_version+1.5.3.tar.gz"
[[libjulia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7cfd9b26f161572c3d0f064c9ad3fa2eba1a66fb"
julia_version = "1.5.3"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "66090148950e541f441867361237150a5e835ecf1c67b1c1fb3d9e534a177d21"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.3+1/libjulia.v1.5.3.armv7l-linux-musleabihf-cxx03-julia_version+1.5.3.tar.gz"
[[libjulia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "557ee81153d3133501d287509d1047ed872194a2"
julia_version = "1.5.3"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "8578d4bf1acdc21bd901d37568d89a33f9fce3f945d603a9508d2ce434e1c8f7"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.3+1/libjulia.v1.5.3.armv7l-linux-musleabihf-cxx11-julia_version+1.5.3.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "abe170fd96bd0d91198fb7bf2eca6a46c69fa93c"
julia_version = "1.5.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "5df26dd85a1af36216c75b4fb863dac48de387804c239844cd352b5175dfb2af"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.3+1/libjulia.v1.5.3.i686-linux-gnu-cxx03-julia_version+1.5.3.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd1267d2ac35ab92d6777ddeec7e9c6de39bfa8f"
julia_version = "1.5.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "15fb244a3a0d2d9685cf69f0f5ed63d0e166e23fb4684b5de5b89a22c47c5a60"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.3+1/libjulia.v1.5.3.i686-linux-gnu-cxx11-julia_version+1.5.3.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6fc7fd4ed12e65c0aad2abaefa8ed42d16eb1a7e"
julia_version = "1.5.3"
os = "windows"

    [[libjulia.download]]
    sha256 = "90f7f4bfcdb65f332ba5b9a823e9713cbe3b59993722acb8ea8902ca6695c11d"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.3+1/libjulia.v1.5.3.i686-w64-mingw32-cxx03-julia_version+1.5.3.tar.gz"
[[libjulia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6db606821b24cb567376c15047c11e8f5cd057fc"
julia_version = "1.5.3"
os = "windows"

    [[libjulia.download]]
    sha256 = "1cc0840931beb013c2809252edb0e673f34386ef0916b282bab129c456187f4a"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.3+1/libjulia.v1.5.3.i686-w64-mingw32-cxx11-julia_version+1.5.3.tar.gz"
[[libjulia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9fe17f334a6aacdddf3100c6ccb078cfe30373f3"
julia_version = "1.5.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "a6cd9f2caeba8642c94697b96b5ea11f680d475fb64aa5de6d85a935d45e5f0e"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.3+1/libjulia.v1.5.3.powerpc64le-linux-gnu-cxx03-julia_version+1.5.3.tar.gz"
[[libjulia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7519ca91dea983198820d5212aaffcc5b6fd4549"
julia_version = "1.5.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "9245e7b58d8017f2a8f1071e8244e39977fd2a51502618ae74b2af0cb3c23923"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.3+1/libjulia.v1.5.3.powerpc64le-linux-gnu-cxx11-julia_version+1.5.3.tar.gz"
[[libjulia]]
arch = "x86_64"
git-tree-sha1 = "454b9eebb04a06599ea9177e4af9b7a0e846a5b7"
julia_version = "1.5.3"
os = "macos"

    [[libjulia.download]]
    sha256 = "61cbc8a883c1e0bcbef0aa1f5a0858937b11f9340eb47d36a5528c0e046c9be7"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.3+1/libjulia.v1.5.3.x86_64-apple-darwin-julia_version+1.5.3.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d8820ceb128a7fe563b92c274ad7d52e98c27c6e"
julia_version = "1.5.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "6ae9f87439807fa11f396eea16ca4fcb9c005b9fb068d09b3c31eea6ff2d9edb"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.3+1/libjulia.v1.5.3.x86_64-linux-gnu-cxx03-julia_version+1.5.3.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "834e72e761399dd3919a093c8a979a62daf84790"
julia_version = "1.5.3"
libc = "glibc"
os = "linux"

    [[libjulia.download]]
    sha256 = "a096e4fb6eb8a8d1c85c777445ef5c267490df7eb10fd30f8ae6a2237e91c9d4"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.3+1/libjulia.v1.5.3.x86_64-linux-gnu-cxx11-julia_version+1.5.3.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "86f39b9936ac595799e6890edd1c68094a95a04c"
julia_version = "1.5.3"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "5f8b6f69fae45dda4a2359335e9c517720c2fa6d821f138d6a00845df0d6c381"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.3+1/libjulia.v1.5.3.x86_64-linux-musl-cxx03-julia_version+1.5.3.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c80b672a05ecaddeaa5d8fbb5bcd8cbff1336e8"
julia_version = "1.5.3"
libc = "musl"
os = "linux"

    [[libjulia.download]]
    sha256 = "51893de3275eeb37545c323cc24fa1d011a4441c29d4921dc6921c21ef383002"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.3+1/libjulia.v1.5.3.x86_64-linux-musl-cxx11-julia_version+1.5.3.tar.gz"
[[libjulia]]
arch = "x86_64"
git-tree-sha1 = "1b67c2c8af58d2aa133b67fddd2a11963ddcfbcd"
julia_version = "1.5.3"
os = "freebsd"

    [[libjulia.download]]
    sha256 = "7a8ee469021648a70a238dc17b757201011aab157951b6341d748893e37736c6"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.3+1/libjulia.v1.5.3.x86_64-unknown-freebsd-julia_version+1.5.3.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bd4afa9da7cc9f4ebb7ff08d576b25b2c9923d32"
julia_version = "1.5.3"
os = "windows"

    [[libjulia.download]]
    sha256 = "38bb37e39dcdcc127f729a27dab05b568f83894bf4a3fefb95ed427d88651245"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.3+1/libjulia.v1.5.3.x86_64-w64-mingw32-cxx03-julia_version+1.5.3.tar.gz"
[[libjulia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55f185728b2742d44ec7f60af9abe7091325aa4b"
julia_version = "1.5.3"
os = "windows"

    [[libjulia.download]]
    sha256 = "8af1d870d717c97cea7433f8bca06a88e2b5aa01dbf911cfe951219660b197c6"
    url = "https://github.com/JuliaBinaryWrappers/libjulia_jll.jl/releases/download/libjulia-v1.5.3+1/libjulia.v1.5.3.x86_64-w64-mingw32-cxx11-julia_version+1.5.3.tar.gz"
