# Autogenerated wrapper script for libjulia_jll for armv7l-linux-gnueabihf-cxx11-julia_version+1.6.0
export libjulia

using LibUnwind_jll
using PCRE2_jll
using OpenLibm_jll
using dSFMT_jll
using LibUV_jll
using utf8proc_jll
using MbedTLS_jll
using LibSSH2_jll
using LibCURL_jll
using Zlib_jll
using p7zip_jll
using MPFR_jll
using GMP_jll
using Objconv_jll
using LibOSXUnwind_jll
using SuiteSparse_jll
using OpenBLAS_jll
using libLLVM_jll
using LibGit2_jll
JLLWrappers.@generate_wrapper_header("libjulia")
JLLWrappers.@declare_library_product(libjulia, "libjulia.so.1")
function __init__()
    JLLWrappers.@generate_init_header(LibUnwind_jll, PCRE2_jll, OpenLibm_jll, dSFMT_jll, LibUV_jll, utf8proc_jll, MbedTLS_jll, LibSSH2_jll, LibCURL_jll, Zlib_jll, p7zip_jll, MPFR_jll, GMP_jll, Objconv_jll, LibOSXUnwind_jll, SuiteSparse_jll, OpenBLAS_jll, libLLVM_jll, LibGit2_jll)
    JLLWrappers.@init_library_product(
        libjulia,
        "lib/libjulia.so",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
